/**
 * Created by mparzych004 on 28.10.2019.
 */

public with sharing class ApDatabaseExample {


    public static void qaz() {
//        String s = 'select Id, Name from Account limit 10';
//        List<Account> l = [select Id, Name from Account limit 10];
//        for (Account ac: l) {
//            ac.Name = ac.Name + 'xcv';
//        }
//        Database.update(l, false);

//        for (Account a : [select RecordType from Account]) {
//
//        }

    }

    public void m() {
        qaz();
    }
}

