
public with sharing class schedul223 implements Schedulable {

    public void execute(SchedulableContext param1) {
//        Account[] l = [select Id, Name from Account];
//        System.debug(l);

//        Account a = [select Name from Account limit 1];
//        Account[] l2  = [a];
//        Integer[] i1 = new Integer[]{1,2,3};
//        Integer[] i2 = new int[]{1,2,3};
//        Integer[] ints2 = new int[]{1, 2, 3};

//        List<Account> l = [select Account.name from Contact];



//        Set<Integer> s = new Set<Integer>({1,3,4});


    }
}
